sudo: false

language: php

env:
  global:
    - COMPOSER_NO_INTERACTION=1
    - COMPOSER_PREFER_LOWEST=0

matrix:
  include:
    - php: 7.0
    - php: 7.0
      env: COMPOSER_PREFER_LOWEST=1
    - php: 7.1
    - php: 7.1
      env: COMPOSER_PREFER_LOWEST=1
    - php: 7.2
    - php: 7.2
      env: COMPOSER_PREFER_LOWEST=1
    - php: 7.3
    - php: 7.3
      env: COMPOSER_PREFER_LOWEST=1
    - php: nightly
    - php: nightly
      env: COMPOSER_PREFER_LOWEST=1
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

before_install:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update

install:
  - if [[ $COMPOSER_PREFER_LOWEST == 0 ]]; then composer update; fi
  - if [[ $COMPOSER_PREFER_LOWEST == 1 ]]; then composer update --prefer-lowest; fi
